In [95]:
import numpy as np

_Создадим признаки._

In [96]:
X1 = np.array([20, 24, 35, 52])
X2 = np.array([120, 140, 150, 160])
X3 = np.array([1, 1, 1, 1])

_Обозначим коэффициенты, которые хотим найти._

In [97]:
Y = 7 * X1 + 5 * X2 + 2 * X3 #вектор (4,)
Y

array([ 742,  870,  997, 1166])

_Обозначим таблицу с данными._

In [98]:
X = np.column_stack([X1, X2])
# X = np.stack([X1,X2], axis=1)
# X = np.c_[X1, X2]
X

array([[ 20, 120],
       [ 24, 140],
       [ 35, 150],
       [ 52, 160]])

_Создадим случайные веса._

In [99]:
w = np.zeros(X.shape[1] + 1)
w

array([0., 0., 0.])

### **Функция полно пакетного градиентного спуска.**

In [100]:
lr = 0.01
def grad(X, w, Y, lr):
    #посчитаем предсказание для каждого объекта
    pred = X @ w
    #найдем ошибку по каждому объекту
    error = (pred - Y)[:, None]
    #найдем средний градиент для каждого признака
    grads = 2 * (X * error).mean(axis=0)
    #изменим вес в соответствии с градиентом
    w = w - grads * lr
    return w

_Запустим обучение в цикле._

In [101]:
# epohs = 100000
# for _ in range(epohs):
#     w = grad(X, w, Y, lr)
#     pred = np.c_[X, np.ones(X.shape[0])] @ w
# print(w)

_Коэффициент b обучается намного медленнее остальных, так как разница между признаками Х1 Х2 и Х3 значительна. Для этого мы приведем все наши данные кроме b к одинаковым единицам измерения - количество стандартных отклонений от среднего значения._

### **Функция для стандартизации данных**

In [102]:
def standart(features):
    #посчитаем средние значения
    f_means = features.mean(axis=0) #вектор
    #найдем квадраты отклонения от среднего
    f_deviation = (features - f_means)**2 #матрица
    #найдем среднее квадратов отклонений - дисперсия
    f_variance = f_deviation.mean(axis=0) #вектор
    #вычислим стандартное отклонение
    f_std = f_variance**0.5 #вектор
    #стандартизируем признаки
    f_stand = (features - f_means) / f_std #матрица
    return f_stand

_Стандартизируем признаки._

In [103]:
X_stand = standart(X)
#также добавим свободный коэффициент обратно
X_stand = np.c_[X_stand, np.ones(X_stand.shape[0])]
X_stand

array([[-1.0284683 , -1.52127766,  1.        ],
       [-0.70581158, -0.16903085,  1.        ],
       [ 0.18149441,  0.50709255,  1.        ],
       [ 1.55278548,  1.18321596,  1.        ]])

_Снова запустим обучение. На обновленных признаках._

In [104]:
epohs = 10000
for _ in range(epohs):

    w = grad(X_stand, w, Y, lr)
    pred = X_stand @ w
print(w.round(1))

[ 86.8  74.  943.7]


_Полученные веса значительно отличаются от наших, потому для проверки применим их к исходным данным._

In [105]:
X_stand @ w, Y

(array([ 741.99999999,  870.00000001,  997.00000001, 1165.99999999]),
 array([ 742,  870,  997, 1166]))