In [3]:
import numpy as np
x1 = np.array([2, 13, 8, 5, 9])
x2 = np.array([8, 15, 24, 18, 7])
y = 8 * x1 + 14 * x2

In [4]:
x1, x2, y

(array([ 2, 13,  8,  5,  9]),
 array([ 8, 15, 24, 18,  7]),
 array([128, 314, 400, 292, 170]))

In [6]:
mx = np.column_stack((x1, x2))
mx

array([[ 2,  8],
       [13, 15],
       [ 8, 24],
       [ 5, 18],
       [ 9,  7]])

In [26]:
w = np.array([1, 1])
lr = 1e-3
ep = 1000
for _ in range(ep):
    pr = mx @ w.T
    er = (pr - y)[:, None]
    gr = np.mean(2 * er * mx, axis=0)
    w = w - lr * gr
    print(w)
w

[4.8516 8.9944]
[ 6.39680592 12.17337728]
[ 7.02300504 13.43447121]
[ 7.28282235 13.93180475]
[ 7.39638575 14.12507535]
[ 7.45138487 14.19738184]
[ 7.48275714 14.22165036]
[ 7.50442782 14.22692391]
[ 7.52195245 14.22476644]
[ 7.53755251 14.21977988]
[ 7.55212126 14.2137932 ]
[ 7.56602262 14.20753104]
[ 7.57940941 14.20127824]
[ 7.59235016 14.1951446 ]
[ 7.60487956 14.18917032]
[ 7.6170186  14.18336796]
[ 7.62878262 14.17773921]
[ 7.64018444 14.1722815 ]
[ 7.65123573 14.16699068]
[ 7.66194746 14.16186207]
[ 7.67233014 14.15689086]
[ 7.68239392 14.15207228]
[ 7.6921486  14.14740168]
[ 7.70160368 14.14287452]
[ 7.71076836 14.1384864 ]
[ 7.71965157 14.13423305]
[ 7.72826194 14.13011034]
[ 7.73660786 14.12611424]
[ 7.74469746 14.12224088]
[ 7.7525386  14.11848648]
[ 7.76013891 14.11484739]
[ 7.76750579 14.11132007]
[ 7.77464641 14.10790108]
[ 7.78156772 14.10458711]
[ 7.78827646 14.10137491]
[ 7.79477915 14.09826137]
[ 7.80108212 14.09524346]
[ 7.80719151 14.09231823]
[ 7.81311326 14.089482

array([ 8., 14.])